kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/yuanshuhan/etcd

steps:

- name: docker  
  image: plugins/docker
  settings:
    username: cn-north-1@HYhvz1QTHxH5qlPbGCFW
    password: 4c10d0c191f41e720055a4aad1008e3a083eff007dc08b1e112342fd6cef6735
    auto_tag: true
    repo: swr.cn-north-1.myhuaweicloud.com/yuanlei/dronetest
    dockerfile: ./Dockerfile
