kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/yuanshuhan/etcd

steps:

- name: docker  
  image: plugins/docker
  settings:
    username: yuanshuhan
    password: 198412cocoyuan
    auto_tag: true
    repo: yuanshuhan/dronetest
    dockerfile: ./Dockerfile
