kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/octocat/hello-world

steps:
- name: test
  image: golang
  commands:
  - go get
  - go test

- name: docker  
  image: plugins/docker
  settings:
    username: kevinbacon
    password: pa55word
    auto_tag: true
    repo: swr.cn-north-1.myhuaweicloud.com/yuanlei/dronetest
    dockerfile: ./Dockerfile
